### ISSUE TITLE
The definition of idempotent is incorrect

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/html-forms#3]
The definition of idempotent given in this lab is:

> the browser can run it repeatedly without changing information on the back-end

This is incorrect. While operations that do not change information on the backend are idempotent, idempotent operations do not necessarily mean that no information on the backend is changed. A good example of this is the fact that PUT is an idempotent http method, and it potentially does change backend data.

A correct definition of `idempotent` as it relates to http can be found at [this website](https://restfulapi.net/idempotent-rest-apis/), which gives this definition:

> An idempotent HTTP method is an HTTP method that can be called many times without different outcomes. It would not matter if the method is called only once, or ten times over. The result should be the same. It essentially means that the result of a successfully performed request is independent of the number of times it is executed. For example, in arithmetic, adding zero to a number is idempotent operation.

The site goes on to describe each http method and how it is/is not idempotent.

For example, PUT is idempotent even though it may affect the backend because it can be run any number of times and all that occurs is that that one entry is ensured to have the value changed by the PUT operation. On the other hand, multiple POST operations will continue adding a new row to a database for each time the POST operation is executed.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
